### ISSUE TITLE
在服务列表页面如何才能显示出各个服务的状态

### ISSUE THREAD

**Issue by imshuai** [go-gost/gostctl#2]
就如示例图片中，各个服务都有显示状态信息，但我安装并连接到API后，状态那里一直是N/A

在配置文件中也配置了`metrics`：
```
api:
  addr: :10110
metrics:
  addr: :20200
  path: /metrics
```
